# Generated by Django 5.2.17 on 2026-09-18 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('accounts', '0003_email_normalise_and_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandfatheredEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grandfathered', to='account.emailaddress')),
            ],
        ),
    ]
