# Generated by Django 5.2.17 on 2026-09-14 15:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0006_learningusageevent'),
        ('assistant', '0002_realtime_transcription_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_key', models.CharField(blank=True, max_length=60)),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill the blank'), ('choose_phrase', 'Choose the correct phrase'), ('rewrite', 'Rewrite the sentence'), ('short_correction', 'Short correction')], max_length=20)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('open_ended', models.BooleanField(default=False, help_text='Many correct formulations: may need AI evaluation.')),
                ('explanation_ro', models.TextField()),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('uk_context', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('generated', 'Generated'), ('editorial', 'Editorial')], max_length=10)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('times_shown', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('usage_event', models.ForeignKey(blank=True, help_text='The generation call (tokens and cost).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='analytics.learningusageevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MistakeOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('pattern_key', models.CharField(max_length=60)),
                ('occurred_at', models.DateTimeField()),
                ('correction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_occurrence', to='assistant.grammarcorrection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_occurrences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('today', 'Today'), ('pattern', 'Pattern')], max_length=10)),
                ('pattern_key', models.CharField(blank=True, max_length=60)),
                ('exercise_ids', models.JSONField(default=list)),
                ('exercise_patterns', models.JSONField(default=list, help_text="The learner's pattern each exercise practises.")),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_key', models.CharField(blank=True, max_length=60)),
                ('answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('graded_by', models.CharField(choices=[('deterministic', 'Deterministic'), ('ai', 'AI evaluation'), ('unverified', 'Not verified')], max_length=13)),
                ('feedback_ro', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.practicesession')),
            ],
        ),
        migrations.CreateModel(
            name='UserMistakePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('pattern_key', models.CharField(max_length=60)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('recent_occurrence_count', models.PositiveIntegerField(default=0, help_text='Last 30 days.')),
                ('previous_period_count', models.PositiveIntegerField(default=0, help_text='The 30 days before that.')),
                ('successful_practice_count', models.PositiveIntegerField(default=0)),
                ('failed_practice_count', models.PositiveIntegerField(default=0)),
                ('mastery', models.PositiveSmallIntegerField(default=0, help_text='0–100, from practice accuracy and time without the mistake.')),
                ('recurrence_score', models.FloatField(default=0)),
                ('priority_score', models.FloatField(default=0)),
                ('review_step', models.PositiveSmallIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('last_practised_at', models.DateTimeField(blank=True, null=True)),
                ('last_mastered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('recurring', 'Recurring'), ('improving', 'Improving'), ('mastered', 'Mastered'), ('resurfaced', 'Resurfaced')], default='new', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_patterns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['user', 'pattern_key', 'retired_at'], name='learning_exercise_pool_idx'),
        ),
        migrations.AddIndex(
            model_name='mistakeoccurrence',
            index=models.Index(fields=['user', 'pattern_key', 'occurred_at'], name='learning_occ_pattern_idx'),
        ),
        migrations.AddIndex(
            model_name='mistakeoccurrence',
            index=models.Index(fields=['user', 'occurred_at'], name='learning_occ_user_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', '-started_at'], name='learning_session_user_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'pattern_key', 'created_at'], name='learning_attempt_pattern_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'created_at'], name='learning_attempt_user_idx'),
        ),
        migrations.AddIndex(
            model_name='usermistakepattern',
            index=models.Index(fields=['user', '-priority_score'], name='learning_pattern_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='usermistakepattern',
            index=models.Index(fields=['user', 'next_review_at'], name='learning_pattern_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermistakepattern',
            constraint=models.UniqueConstraint(fields=('user', 'pattern_key'), name='unique_user_mistake_pattern'),
        ),
    ]
