# Generated by Django 5.2.17 on 2026-09-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='mastery_at_start',
            field=models.JSONField(blank=True, default=dict, help_text="Each practised pattern's mastery when the session started."),
        ),
    ]
