from django.contrib import admin
from django.urls import reverse
from django.utils.html import format_html

from .formatting import format_money
from .identifiers import visitor_lookup
from .models import AnonymousVisitor, AudioUsageEvent, UsageEvent


class LedgerAdmin(admin.ModelAdmin):
    """Usage records are an audit trail generated by the app: viewable, never added or edited by hand."""

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return request.user.is_superuser


class LedgerIdentityMixin:
    """Shows who a ledger row belongs to and lets staff search by username, email or visitor ID."""

    search_fields = ["user__username", "user__email", "error_code"]
    search_help_text = "Username, email, error code, visitor UUID or anon-xxxxxx"
    date_hierarchy = "created_at"
    list_select_related = ["user", "visitor"]
    list_per_page = 100
    show_full_result_count = False

    def get_search_results(self, request, queryset, search_term):
        results, may_have_duplicates = super().get_search_results(request, queryset, search_term)
        lookup = visitor_lookup(search_term, "visitor_id") if search_term.strip() else None
        if lookup is not None:
            results = results | queryset.filter(lookup)
        return results, may_have_duplicates

    @admin.display(description="User / visitor", ordering="user__username")
    def identity(self, obj):
        if obj.user_id:
            return obj.user.get_username()
        if obj.visitor_id:
            return obj.visitor.short_id
        return "deleted user" if obj.audience == UsageEvent.Audience.REGISTERED else "—"


@admin.register(UsageEvent)
class UsageEventAdmin(LedgerIdentityMixin, LedgerAdmin):
    list_display = ["created_at", "identity", "request_type", "auto_translated", "status", "error_code", "model",
                    "input_tokens", "output_tokens", "total_tokens", "cost"]
    list_filter = ["audience", "request_type", "status", "model", "auto_translated", "is_backfilled", "created_at"]

    @admin.display(description="Text AI cost", ordering="estimated_cost")
    def cost(self, obj):
        return format_money(obj.estimated_cost)


@admin.register(AudioUsageEvent)
class AudioUsageEventAdmin(LedgerIdentityMixin, LedgerAdmin):
    list_display = ["id", "created_at", "operation", "audience", "identity", "speech_target", "model", "voice", "status",
                    "error_code", "audio_seconds", "input_tokens", "output_tokens", "cost"]
    list_filter = ["operation", "audience", "model", "voice", "status", "speech_target", "created_at"]

    @admin.display(description="Audio AI cost", ordering="estimated_cost")
    def cost(self, obj):
        return format_money(obj.estimated_cost)


@admin.register(AnonymousVisitor)
class AnonymousVisitorAdmin(LedgerAdmin):
    list_display = ["short_id", "first_seen_at", "last_seen_at", "converted_user", "converted_via", "converted_at",
                    "analytics"]
    list_filter = ["converted_via", ("converted_user", admin.EmptyFieldListFilter), "first_seen_at"]
    search_fields = ["converted_user__username", "converted_user__email"]
    search_help_text = "Converted username or email, visitor UUID or anon-xxxxxx"
    date_hierarchy = "first_seen_at"
    list_select_related = ["converted_user"]

    def get_search_results(self, request, queryset, search_term):
        results, may_have_duplicates = super().get_search_results(request, queryset, search_term)
        lookup = visitor_lookup(search_term) if search_term.strip() else None
        if lookup is not None:
            results = results | queryset.filter(lookup)
        return results, may_have_duplicates

    @admin.display(description="Visitor", ordering="id")
    def short_id(self, obj):
        return obj.short_id

    @admin.display(description="Usage")
    def analytics(self, obj):
        return format_html('<a href="{}">View usage</a>', reverse("analytics:visitor", args=[obj.pk]))
