# Generated by Django 5.2.17 on 2026-09-13 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('correction', 'Correction'), ('translation', 'Translation')], max_length=12)),
                ('original_text', models.TextField(blank=True)),
                ('result_text', models.TextField(blank=True)),
                ('detected_language', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField()),
                ('replacement', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('severity', models.CharField(max_length=15)),
                ('explanation_ro', models.TextField()),
                ('is_british_preference', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='assistant.assistantrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=70)),
                ('token', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'token'), name='unique_actor_submission')],
            },
        ),
        migrations.AddIndex(
            model_name='assistantrequest',
            index=models.Index(fields=['user', '-created_at'], name='assistant_a_user_id_ab9458_idx'),
        ),
    ]
