# Generated by Django 5.2.17 on 2026-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_realtime_transcription_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantrequest',
            name='request_type',
            field=models.CharField(choices=[('correction', 'Correction (English)'), ('translation', 'Translation into British English'), ('unclassified', 'Unclassified (failed before the language was known)')], max_length=12),
        ),
    ]
