# Generated by Django 5.2.17 on 2026-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_request_type_unclassified'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalizeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=70)),
                ('day', models.DateField(db_index=True)),
                ('used', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'day'), name='unique_actor_naturalize_day')],
            },
        ),
    ]
