# Generated by Django 5.2.17 on 2026-09-13 19:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_via', models.CharField(blank=True, choices=[('signup', 'Signup'), ('login', 'Sign-in')], max_length=10)),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('registered', 'Registered'), ('anonymous', 'Anonymous')], max_length=10)),
                ('request_type', models.CharField(choices=[('correction', 'Correction'), ('translation', 'Translation')], help_text='The action the visitor chose.', max_length=12)),
                ('auto_translated', models.BooleanField(default=False, help_text='Romanian sent to Correct and translated instead.')),
                ('model', models.CharField(blank=True, help_text='Configured OPENAI_MODEL.', max_length=100)),
                ('response_model', models.CharField(blank=True, help_text='Model name reported by the provider.', max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected')], max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('provider_calls', models.PositiveSmallIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('reasoning_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=8, help_text='USD at recording time; empty when pricing or tokens are unknown.', max_digits=14, null=True)),
                ('is_backfilled', models.BooleanField(default=False, help_text='Created from history saved before usage tracking.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('assistant_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_event', to='assistant.assistantrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='analytics.anonymousvisitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='anonymousvisitor',
            index=models.Index(fields=['first_seen_at'], name='analytics_visitor_first_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', '-created_at'], name='analytics_usage_user_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['visitor', '-created_at'], name='analytics_usage_visitor_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['audience', 'created_at'], name='analytics_usage_audience_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['status', 'created_at'], name='analytics_usage_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['request_type', 'created_at'], name='analytics_usage_type_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['model'], name='analytics_usage_model_idx'),
        ),
    ]
