# Generated by Django 5.2.17 on 2026-09-13 20:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_backfill_assistant_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('transcription', 'Voice input (speech to text)'), ('speech', 'Voice output (text to speech)')], max_length=13)),
                ('audience', models.CharField(choices=[('registered', 'Registered'), ('anonymous', 'Anonymous')], max_length=10)),
                ('speech_target', models.CharField(blank=True, choices=[('correction', 'Correction'), ('native', 'Native version')], max_length=10)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('voice', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected')], max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('provider_calls', models.PositiveSmallIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Provider-reported duration of transcribed audio.', max_digits=8, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=8, help_text='USD at recording time; empty when pricing or usage is unknown.', max_digits=14, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usage_event', models.ForeignKey(blank=True, help_text='The correction that was spoken.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_usage_events', to='analytics.usageevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_usage_events', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_usage_events', to='analytics.anonymousvisitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', 'created_at'], name='analytics_audio_op_idx'), models.Index(fields=['user', '-created_at'], name='analytics_audio_user_idx'), models.Index(fields=['visitor', '-created_at'], name='analytics_audio_visitor_idx'), models.Index(fields=['audience', 'created_at'], name='analytics_audio_audience_idx'), models.Index(fields=['model', 'created_at'], name='analytics_audio_model_idx'), models.Index(fields=['status', 'created_at'], name='analytics_audio_status_idx')],
            },
        ),
    ]
