# Generated by Django 5.2.17 on 2026-09-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_audiousageevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiousageevent',
            name='speech_target',
            field=models.CharField(blank=True, choices=[('correction', 'Correction'), ('native', 'Native version'), ('translation', 'Translation into English')], max_length=12),
        ),
    ]
