# Generated by Django 5.2.17 on 2026-09-13 22:01

from django.conf import settings
from django.db import migrations, models


def mark_existing_transcriptions(apps, schema_editor):
    """Live transcription did not exist before this migration, so every earlier transcription was a finished recording
    whose duration the server read from the provider's response. Costs are left exactly as recorded."""
    AudioUsageEvent = apps.get_model("analytics", "AudioUsageEvent")
    AudioUsageEvent.objects.filter(operation="transcription", stt_mode="", audio_seconds__isnull=False,
                                   metering_source="").update(metering_source="provider")
    AudioUsageEvent.objects.filter(operation="transcription", stt_mode="").update(stt_mode="file")


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_speech_target_translation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiousageevent',
            name='metering_source',
            field=models.CharField(blank=True, choices=[('provider', 'Provider-reported duration'), ('stream_duration', 'Server-observed session window')], help_text='Where the audio duration came from.', max_length=16),
        ),
        migrations.AddField(
            model_name='audiousageevent',
            name='stt_mode',
            field=models.CharField(blank=True, choices=[('file', 'File (after recording)'), ('realtime', 'Realtime (live)')], help_text='Speech to text only: live in the browser, or a finished recording.', max_length=8, verbose_name='transcription mode'),
        ),
        migrations.AlterField(
            model_name='audiousageevent',
            name='audio_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration of transcribed audio; see the metering source.', max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='audiousageevent',
            index=models.Index(fields=['stt_mode', 'created_at'], name='analytics_audio_stt_mode_idx'),
        ),
        migrations.RunPython(mark_existing_transcriptions, migrations.RunPython.noop),
    ]
