# Generated by Django 5.2.17 on 2026-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_learningusageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiousageevent',
            name='connect_ms',
            field=models.PositiveIntegerField(blank=True, help_text='WebRTC connection to the provider.', null=True),
        ),
        migrations.AddField(
            model_name='audiousageevent',
            name='final_received',
            field=models.BooleanField(blank=True, help_text='Whether the final transcript arrived before the safety timeout.', null=True),
        ),
        migrations.AddField(
            model_name='audiousageevent',
            name='finalise_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Stop to final transcript.', null=True),
        ),
        migrations.AddField(
            model_name='audiousageevent',
            name='first_word_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Listening to the first transcribed words.', null=True),
        ),
        migrations.AddField(
            model_name='audiousageevent',
            name='mic_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Microphone press to microphone ready.', null=True),
        ),
        migrations.AddField(
            model_name='audiousageevent',
            name='provider_duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Server-measured provider call (file transcription, speech).', null=True),
        ),
        migrations.AddField(
            model_name='audiousageevent',
            name='session_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Session request to Corect.uk.', null=True),
        ),
        migrations.AddField(
            model_name='audiousageevent',
            name='startup_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Microphone press to listening.', null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Server time from receiving the request to recording it.', null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='moderation_duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Moderation check, run alongside the provider call.', null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='provider_duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Time spent in the generative provider call.', null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='source_language',
            field=models.CharField(blank=True, help_text='Language the input was classified as (en, ro, other...); empty if unknown.', max_length=12),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='auto_translated',
            field=models.BooleanField(default=False, help_text='Legacy, before the single action: Romanian sent to Correct and translated instead.'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='request_type',
            field=models.CharField(choices=[('correction', 'English correction'), ('translation', 'Translation into British English'), ('unclassified', 'Unclassified')], help_text='Effective operation: correction (English input) or translation (e.g. Romanian into British English); unclassified when the request failed before its language was known.', max_length=12),
        ),
    ]
