# Generated by Django 5.2.17 on 2026-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='polite',
            field=models.BooleanField(default=False, help_text='Sent with „Mod Politicos” switched on.'),
        ),
    ]
