# Generated by Django 5.2.17 on 2026-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_usage_polite'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='from_history',
            field=models.BooleanField(default=False, help_text="Answered from the learner's own saved result for the same text: no provider call, and no use taken from the daily quota."),
        ),
    ]
