# Generated by Django 5.2.17 on 2026-09-17 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_usage_event_from_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('site_visit', 'Visited the site'), ('signup_viewed', 'Opened the signup page'), ('pricing_viewed', 'Saw the plans'), ('pro_cta_clicked', 'Clicked a Pro call to action'), ('checkout_started', 'Started checkout'), ('subscription_started', 'Became a paying customer')], max_length=32)),
                ('placement', models.CharField(blank=True, max_length=32)),
                ('audience', models.CharField(choices=[('registered', 'Registered'), ('anonymous', 'Anonymous')], max_length=10)),
                ('plan', models.CharField(blank=True, choices=[('anonymous', 'Anonymous'), ('free', 'Free'), ('pro', 'Pro')], max_length=10)),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to='analytics.anonymousvisitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'created_at'], name='analytics_funnel_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', True), ('visitor__isnull', True), _connector='XOR'), name='analytics_funnel_one_identity'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('name', 'placement', 'user', 'day'), name='analytics_funnel_user_daily'), models.UniqueConstraint(condition=models.Q(('visitor__isnull', False)), fields=('name', 'placement', 'visitor', 'day'), name='analytics_funnel_visitor_daily')],
            },
        ),
    ]
